/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package group2;

/**
 *
 * @author ADMIN
 */
public class PnTaiKhoan extends javax.swing.JPanel {

    /**
     * Creates new form PnTaiKhoan
     */
    public PnTaiKhoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnTaikhoan = new javax.swing.JPanel();
        cacNuttaikhoan = new javax.swing.JPanel();
        BTxoataikhoan = new javax.swing.JButton();
        BTtatcataikhoan = new javax.swing.JButton();
        BTtaotaikhoan = new javax.swing.JButton();
        cacPanel = new javax.swing.JPanel();
        tatcataikhoan = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Taotaikhoan = new javax.swing.JPanel();
        lableNhapTaiKhoan = new javax.swing.JLabel();
        TFnhapTaiKhoan = new javax.swing.JTextField();
        lableNhapMatKhau = new javax.swing.JLabel();
        TFnhapMatKhau = new javax.swing.JTextField();
        TFnhapLạiMK = new javax.swing.JTextField();
        lableNhapLaiMK = new javax.swing.JLabel();
        TFnhapSDT = new javax.swing.JTextField();
        lableSDT = new javax.swing.JLabel();
        TFnhapSoTien = new javax.swing.JTextField();
        lableSoTienNap = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Xoataikhoan = new javax.swing.JPanel();

        cacNuttaikhoan.setPreferredSize(new java.awt.Dimension(1000, 50));
        cacNuttaikhoan.setLayout(null);

        BTxoataikhoan.setText("Xóa tài khoản");
        BTxoataikhoan.setPreferredSize(new java.awt.Dimension(75, 30));
        BTxoataikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTxoataikhoanActionPerformed(evt);
            }
        });
        cacNuttaikhoan.add(BTxoataikhoan);
        BTxoataikhoan.setBounds(320, 10, 129, 30);

        BTtatcataikhoan.setText("Tất cả tài khoản");
        BTtatcataikhoan.setPreferredSize(new java.awt.Dimension(75, 30));
        BTtatcataikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTtatcataikhoanActionPerformed(evt);
            }
        });
        cacNuttaikhoan.add(BTtatcataikhoan);
        BTtatcataikhoan.setBounds(10, 10, 128, 31);

        BTtaotaikhoan.setText("Tạo tài khoản");
        BTtaotaikhoan.setPreferredSize(new java.awt.Dimension(75, 30));
        BTtaotaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTtaotaikhoanActionPerformed(evt);
            }
        });
        cacNuttaikhoan.add(BTtaotaikhoan);
        BTtaotaikhoan.setBounds(160, 10, 128, 30);

        cacPanel.setLayout(new java.awt.CardLayout());

        tatcataikhoan.setPreferredSize(new java.awt.Dimension(1000, 470));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tatcataikhoan.setViewportView(jTable2);

        cacPanel.add(tatcataikhoan, "card2");

        Taotaikhoan.setLayout(null);

        lableNhapTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lableNhapTaiKhoan.setText("Nhập tài khoản");
        Taotaikhoan.add(lableNhapTaiKhoan);
        lableNhapTaiKhoan.setBounds(340, 50, 130, 20);
        Taotaikhoan.add(TFnhapTaiKhoan);
        TFnhapTaiKhoan.setBounds(500, 40, 250, 30);

        lableNhapMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lableNhapMatKhau.setText("Nhập mật khẩu");
        Taotaikhoan.add(lableNhapMatKhau);
        lableNhapMatKhau.setBounds(340, 90, 130, 20);
        Taotaikhoan.add(TFnhapMatKhau);
        TFnhapMatKhau.setBounds(500, 80, 250, 30);
        Taotaikhoan.add(TFnhapLạiMK);
        TFnhapLạiMK.setBounds(500, 120, 250, 30);

        lableNhapLaiMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lableNhapLaiMK.setText("Nhập lại mật khẩu");
        Taotaikhoan.add(lableNhapLaiMK);
        lableNhapLaiMK.setBounds(340, 130, 130, 22);
        Taotaikhoan.add(TFnhapSDT);
        TFnhapSDT.setBounds(500, 160, 250, 30);

        lableSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lableSDT.setText("Số điện thoại");
        Taotaikhoan.add(lableSDT);
        lableSDT.setBounds(340, 170, 130, 20);
        Taotaikhoan.add(TFnhapSoTien);
        TFnhapSoTien.setBounds(500, 200, 250, 30);

        lableSoTienNap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lableSoTienNap.setText("Số tiền nạp");
        Taotaikhoan.add(lableSoTienNap);
        lableSoTienNap.setBounds(340, 210, 130, 20);

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Nhập lại");
        Taotaikhoan.add(jButton4);
        jButton4.setBounds(640, 250, 110, 30);

        jButton5.setBackground(new java.awt.Color(0, 153, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Xác nhận");
        Taotaikhoan.add(jButton5);
        jButton5.setBounds(500, 250, 110, 30);

        cacPanel.add(Taotaikhoan, "card3");

        Xoataikhoan.setPreferredSize(new java.awt.Dimension(1000, 470));

        javax.swing.GroupLayout XoataikhoanLayout = new javax.swing.GroupLayout(Xoataikhoan);
        Xoataikhoan.setLayout(XoataikhoanLayout);
        XoataikhoanLayout.setHorizontalGroup(
            XoataikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1006, Short.MAX_VALUE)
        );
        XoataikhoanLayout.setVerticalGroup(
            XoataikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        cacPanel.add(Xoataikhoan, "card4");

        javax.swing.GroupLayout PnTaikhoanLayout = new javax.swing.GroupLayout(PnTaikhoan);
        PnTaikhoan.setLayout(PnTaikhoanLayout);
        PnTaikhoanLayout.setHorizontalGroup(
            PnTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnTaikhoanLayout.createSequentialGroup()
                .addComponent(cacNuttaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PnTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cacPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE))
        );
        PnTaikhoanLayout.setVerticalGroup(
            PnTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnTaikhoanLayout.createSequentialGroup()
                .addComponent(cacNuttaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(470, Short.MAX_VALUE))
            .addGroup(PnTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnTaikhoanLayout.createSequentialGroup()
                    .addGap(0, 50, Short.MAX_VALUE)
                    .addComponent(cacPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PnTaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PnTaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTxoataikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTxoataikhoanActionPerformed
        cacPanel.removeAll();
        cacPanel.add(Xoataikhoan);
        cacPanel.revalidate();
        cacPanel.repaint();
    }//GEN-LAST:event_BTxoataikhoanActionPerformed

    private void BTtatcataikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTtatcataikhoanActionPerformed
        cacPanel.removeAll();
        cacPanel.add(tatcataikhoan);
        cacPanel.revalidate();
        cacPanel.repaint();
    }//GEN-LAST:event_BTtatcataikhoanActionPerformed

    private void BTtaotaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTtaotaikhoanActionPerformed
        cacPanel.removeAll();
        cacPanel.add(Taotaikhoan);
        cacPanel.revalidate();
        cacPanel.repaint();
    }//GEN-LAST:event_BTtaotaikhoanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTtaotaikhoan;
    private javax.swing.JButton BTtatcataikhoan;
    private javax.swing.JButton BTxoataikhoan;
    private javax.swing.JPanel PnTaikhoan;
    private javax.swing.JTextField TFnhapLạiMK;
    private javax.swing.JTextField TFnhapMatKhau;
    private javax.swing.JTextField TFnhapSDT;
    private javax.swing.JTextField TFnhapSoTien;
    private javax.swing.JTextField TFnhapTaiKhoan;
    private javax.swing.JPanel Taotaikhoan;
    private javax.swing.JPanel Xoataikhoan;
    private javax.swing.JPanel cacNuttaikhoan;
    private javax.swing.JPanel cacPanel;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lableNhapLaiMK;
    private javax.swing.JLabel lableNhapMatKhau;
    private javax.swing.JLabel lableNhapTaiKhoan;
    private javax.swing.JLabel lableSDT;
    private javax.swing.JLabel lableSoTienNap;
    private javax.swing.JScrollPane tatcataikhoan;
    // End of variables declaration//GEN-END:variables
}
